# Generated by Django 2.2.1 on 2019-05-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cancha', models.CharField(default='001', max_length=3)),
                ('descripcion_cancha', models.TextField(default='cancha de futbolito', max_length=150)),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_noche', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('estado_cancha', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(default='000123', max_length=6)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField(default='12:00')),
                ('valor_untario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('estado_reserva', models.BooleanField(default=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Cancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complejo', models.CharField(default='Complejo Deportivo ', max_length=40)),
                ('direccion_complejo', models.TextField(default='sector-calle principal-calle secundaria-nro-referencia', max_length=200)),
                ('telefono_complejo', models.CharField(default='(+593) 098-234-1334', max_length=19)),
                ('cantidad_canchas', models.IntegerField()),
                ('puntuacion_complejo', models.IntegerField(default='5')),
                ('estado_complejo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Complejo'),
        ),
    ]
