# Generated by Django 3.0.7 on 2020-07-09 03:04

import app1.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cancha', models.CharField(default='Cancha de fútbol Nro 1', max_length=40)),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_noche', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('foto_cancha', models.ImageField(blank=True, null=True, upload_to='images/canchas_images', validators=[app1.validators.valid_extension])),
                ('estado_cancha', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complejo', models.CharField(default='Complejo Deportivo', max_length=40)),
                ('direccion_complejo', models.TextField(default='sector-calle principal-calle secundaria-nro-referencia', max_length=200)),
                ('telefono_complejo', models.CharField(default='(+593) 098-234-1334', max_length=19)),
                ('puntuacion_complejo', models.IntegerField(default='5')),
                ('foto_complejo', models.ImageField(blank=True, null=True, upload_to='images/complejos_images', validators=[app1.validators.valid_extension])),
                ('coordenadas_complejo', models.CharField(blank=True, max_length=250, null=True)),
                ('hora_apertura', models.TimeField(default='09:00')),
                ('hora_cierre', models.TimeField(default='23:00')),
                ('estado_complejo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=354, null=True)),
                ('puntuacion_usuario', models.IntegerField(default='5')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('suscripcion', models.BooleanField(default=False, null=True)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Complejo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default='12:00')),
                ('hora_fin', models.TimeField(default='13:00')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('estado_reserva', models.BooleanField(default=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Cancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Complejo'),
        ),
    ]
