# Generated by Django 2.2.1 on 2019-05-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_cancha',
            field=models.IntegerField(),
        ),
    ]
