# Generated by Django 2.2.1 on 2019-05-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(limit_choices_to={'usuario_id': 'auth.User'}, on_delete=django.db.models.deletion.CASCADE, related_name='cancha_complejo', to='app1.Complejo'),
        ),
    ]
