# Generated by Django 2.2.1 on 2019-05-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190520_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complejo',
            name='cantidad_canchas',
        ),
        migrations.AlterField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Complejo'),
        ),
    ]
