# Generated by Django 2.2.1 on 2019-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190514_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.TextField(max_length=6, null=True),
        ),
    ]
