# Generated by Django 2.2.1 on 2019-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_reserva_codigo_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
