# Generated by Django 2.2.1 on 2019-06-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190522_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_reserva',
            new_name='hora_inicio',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='valor_untario',
            new_name='valor_unitario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default='13:00'),
        ),
    ]
