# Generated by Django 2.2.1 on 2019-05-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190514_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=models.CharField(default='000123', max_length=6, null=True),
        ),
    ]
