# Generated by Django 2.2.1 on 2019-07-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190620_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='codigo_cancha',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='codigo_reserva',
        ),
        migrations.AddField(
            model_name='cancha',
            name='foto_cancha',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complejo',
            name='coordenadas_complejo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complejo',
            name='foto_complejo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complejo',
            name='hora_apertura',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='complejo',
            name='hora_cierre',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='descripcion_cancha',
            field=models.TextField(default='Cancha de fútbol Nro 1', max_length=150),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='valor_noche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='nombre_complejo',
            field=models.CharField(default='Complejo Deportivo', max_length=40),
        ),
    ]
