# Generated by Django 2.2.1 on 2019-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190514_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='numero_cancha',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_reserva',
            field=models.TimeField(default='12:00'),
        ),
    ]
