# Generated by Django 2.2.1 on 2019-05-15 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190514_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cancha', models.CharField(default='001', max_length=3)),
                ('descripcion_cancha', models.TextField(default='cancha de futbolito', max_length=150)),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_noche', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('estado_cancha', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Cancha'),
        ),
    ]
