# Generated by Django 2.2.1 on 2019-07-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190705_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='valor_noche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
