# Generated by Django 2.2.1 on 2019-07-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20190705_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='foto_cancha',
            field=models.ImageField(blank=True, null=True, upload_to='images/canchas_images'),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='foto_complejo',
            field=models.ImageField(blank=True, null=True, upload_to='images/complejos_images'),
        ),
    ]
