# Generated by Django 2.2.1 on 2019-07-26 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0008_auto_20190712_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=354, null=True)),
                ('puntuacion_usuario', models.IntegerField(default='5')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('suscripcion', models.BooleanField(default=False, null=True)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Complejo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
