# Generated by Django 2.2.1 on 2019-05-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20190514_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_complejo', models.CharField(default='Complejo Deportivo ', max_length=20)),
                ('direccion_complejo', models.TextField(default='sector-calle principal-calle secundaria-nro-referencia', max_length=200)),
                ('telefono_complejo', models.CharField(default='(+593) 098-234-1334', max_length=19)),
                ('cantidad_canchas', models.IntegerField()),
                ('puntuacion_complejo', models.IntegerField(default='5')),
                ('estado_complejo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Complejo'),
        ),
    ]
