# Generated by Django 2.2.1 on 2019-05-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20190514_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='complejo',
        ),
    ]
