# Generated by Django 2.2.1 on 2019-05-15 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_cancha_complejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Complejo'),
        ),
        migrations.AlterField(
            model_name='complejo',
            name='nombre_complejo',
            field=models.CharField(default='Complejo Deportivo ', max_length=40),
        ),
    ]
