# Generated by Django 2.2.1 on 2019-05-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20190514_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Complejo'),
        ),
    ]
