# Generated by Django 2.2.1 on 2019-08-14 16:16

import app1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20190813_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complejo',
            name='foto_complejo',
            field=models.ImageField(blank=True, null=True, upload_to='images/complejos_images', validators=[app1.validators.valid_extension]),
        ),
    ]
