# Generated by Django 2.2.1 on 2019-08-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20190814_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='descripcion_cancha',
            field=models.CharField(default='Cancha de fútbol Nro 1', max_length=40),
        ),
    ]
